language: r
sudo: required
dist: trusty
bioc_required: true
services:
- docker
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
    - libudunits2-dev                     # units > ggforce > ggraph > patchwork > dynplot
    - libssh-dev                          # ssh > qsub
git:
  submodules: false
before_install:
 - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
 - install_hdf5
 - install_dynverse
 - cd package
install:
 - install_cran devtools covr
 - install_withdeps
after_success:
 - R -e 'covr::codecov()'

jobs:
  include:
    - stage: prepare cache
      script:
      - echo Skip
      after_success:
      - echo Skip
    - stage: test
